name: guhio
version: 0.1.7
type: app
vendor: Simon Stürz <simon.stuerz@guh.guru>
architecture: ["armhf"]
icon: meta/guh-logo.svg
source: https://github.com/guh/guh
license-version: "GPLv2"
services:
  - name: guhd
    start: usr/bin/guhd-wrapper.sh
    description: "Daemon for the guh IoT server"
    security-template: unconfined
    ports:
        internal:
            jsonrpc:
                port: 2222/tcp
                negotiable: yes
            avahi:
                port: 5353/udp
                negotiable: yes
        external:
            ui:
                port: 3333/tcp
                negotiable: no
            websocket:
                port: 4444/tcp
                negotiable: yes
            upnp:
                port: 1900/udp
                negotiable: yes
binaries:
  - name: guh-cli
    exec: ./usr/bin/guh-cli
    description: "Command line interface for the guh IoT server - python"















